### ISSUE TITLE
update-code-snippets.js not working in Chrome 45.0.2454.101

### ISSUE THREAD

**Issue by jimmygchen** [bahmutov/code-snippets#16]
I'm getting the following error when running the snippet `update-code-snippets.js` to update my snippets:
`Cannot find scriptSnippets, are you running in the secondary DevTools? 
see https://github.com/bahmutov/code-snippets#updating-local-code-snippets`

My Chrome version is 45.0.2454.101 m.

I ran the snippet from the 2nd DevTools instance (following the steps in documentation) but it doesn't work - `scriptSnippets` key doesn't exist in localStorage. It seems that scriptSnippets are no longer stored in localStorage?

My temporary workaround to this problem is to modify the update-code-snippet.js (not nice but works for me atm):
https://gist.github.com/jchen86/3ca08af721a43725ebf6

**Comment by hoto** [comment]
Looks like Chrome removed snippets access from dev tools local storage. This `https://developers.google.com/web/tools/chrome-devtools/debug/snippets/#map-snippets-to-external-files-via-workspaces` says one can map snippets to folder on a disk but i could not recreate that. Only way was to create a Workspace that points to my folder with git repository (with snippets). But files from that folder do not display in `Snippets` tab, only in `Sources tab`.
This woks, and now I can just `git pull` to get latest changes but those files are not carried with my Chrome installations on different machines.

@jchen86 looks like `WebInspector.scriptSnippetModel._snippetStorage.snippets(); ` no longer works in current Chrome distribution.
I could not find what is the new way of accessing snippets in Chrome. 

![image](https://cloud.githubusercontent.com/assets/3105832/12483314/8a8956da-c054-11e5-9a69-2ed215671632.png)
![image](https://cloud.githubusercontent.com/assets/3105832/12483332/a12b32e6-c054-11e5-8be3-fe549528a57c.png)

**Comment by bahmutov** [comment]
Might be same as #23
